api_keys:
  gpt-3.5-turbo-16k:
    - api_key: sk-xxxxx
      organization: org-xxxxx
      model: gpt-3.5-turbo-16k
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-3.5-turbo-16k
  gpt-4:    
    - api_key: sk-xxxxx
      organization: org-xxxxx
      model: gpt-4
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-4

default_request_type: openai
default_completion_kwargs:
  model: gpt-4
  temperature: 0.2
  request_timeout: 60

enable_summary: true
summary:
  single_action_max_length: 1024
  max_return_length: 2048

use_selfhost_toolserver: true
selfhost_toolserver_url: http://localhost:8080

max_retry_times: 3
max_subtask_chain_length: 7
max_plan_refine_chain_length: 3
max_plan_tree_depth: 3
max_plan_tree_width: 5
max_plan_length: 1536

rapidapi_retrieve_tool_count: 0

enable_ask_human_for_help: False

tool_blacklist:
  - FileSystemEnv_print_filesys_struture

record_dir: